services:
  - type: web
    name: sensor-coverage-api-raw
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true
    # Add build timeout for large terrain file
    buildTimeout: 1800 