name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run terrain loading test
      run: |
        python test_terrain_loading.py
        
    - name: Run API test (if terrain data available)
      run: |
        python test/api_test.py
      continue-on-error: true
      
    - name: Check code formatting
      run: |
        pip install black
        black --check .
      continue-on-error: true 